# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags: [ '*' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2 
        with:
          fetch-depth: 0

      - name: Get Current Git Tag
        run: |
          TAG=$(git describe --abbrev=0 --tags)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Display Version (debug)
        run: echo "Trying to use version $TAG"

      - name: Find and Replace Version
        run: find *.nuspec -type f -exec sed -i ''s/#{VERSION}#/$TAG/g'' {} \;

      - name: Choco Pack
        uses: crazy-max/ghaction-chocolatey@v1.4.0
        with:
          args: pack --allow-unofficial

      - name: Choco Push
        uses: crazy-max/ghaction-chocolatey@v1.4.0
        if: github.ref == 'refs/heads/master'
        with:
          args: push memoq.$TAG.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCO_API_KEY }} --allow-unofficial